<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('esewas', function (Blueprint $table) {
            $table->id();

            // Merchant side
            $table->string('transaction_uuid')->unique()->comment('Unique ID generated by merchant');
            $table->decimal('amount', 12, 2);
            $table->string('product_code')->default('INTENT');
            $table->string('callback_url')->nullable();
            $table->string('redirect_url')->nullable();
            $table->json('properties')->nullable()->comment('Extra fields sent to eSewa');

            // eSewa side
            $table->string('booking_id')->nullable()->unique()->comment('Returned by eSewa on book');
            $table->string('correlation_id')->nullable()->comment('Returned by eSewa on book');
            $table->string('deeplink')->nullable();
            $table->string('reference_code')->nullable()->comment('eSewa reference after payment');
            $table->string('esewa_transaction_id')->nullable()->comment('eSewas internal txn ID');

            // Status tracking
            $table->enum('status', [
                'BOOKED',
                'SUCCESS',
                'PENDING',
                'FAILED',
                'CANCELED',
                'REVERTED',
            ])->default('BOOKED');

            $table->json('esewa_response')->nullable()->comment('Full raw response from eSewa');
            $table->timestamp('paid_at')->nullable();
            $table->timestamps();

            // Indexes
            $table->index('status');
            $table->index('booking_id');
            $table->index('transaction_uuid');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('esewas');
    }
};
